//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSoap.ServiceFootballer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFootballer.Services")]
    public interface Services {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.ServiceFootballer.listResponse list(ClienteSoap.ServiceFootballer.listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.listResponse> listAsync(ClienteSoap.ServiceFootballer.listRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.ServiceFootballer.deleteResponse delete(ClienteSoap.ServiceFootballer.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.deleteResponse> deleteAsync(ClienteSoap.ServiceFootballer.deleteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.ServiceFootballer.readResponse read(ClienteSoap.ServiceFootballer.readRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.readResponse> readAsync(ClienteSoap.ServiceFootballer.readRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.ServiceFootballer.createResponse create(ClienteSoap.ServiceFootballer.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.createResponse> createAsync(ClienteSoap.ServiceFootballer.createRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.ServiceFootballer.updateResponse update(ClienteSoap.ServiceFootballer.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.updateResponse> updateAsync(ClienteSoap.ServiceFootballer.updateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class footballer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clubField;
        
        private string forenameField;
        
        private double heightField;
        
        private string idField;
        
        private int numberField;
        
        private string positionField;
        
        private string surnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string club {
            get {
                return this.clubField;
            }
            set {
                this.clubField = value;
                this.RaisePropertyChanged("club");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string forename {
            get {
                return this.forenameField;
            }
            set {
                this.forenameField = value;
                this.RaisePropertyChanged("forename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="list", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listRequest {
        
        public listRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class listResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSoap.ServiceFootballer.footballer[] @return;
        
        public listResponse() {
        }
        
        public listResponse(ClienteSoap.ServiceFootballer.footballer[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public deleteRequest() {
        }
        
        public deleteRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class readRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public readRequest() {
        }
        
        public readRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class readResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSoap.ServiceFootballer.footballer @return;
        
        public readResponse() {
        }
        
        public readResponse(ClienteSoap.ServiceFootballer.footballer @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSoap.ServiceFootballer.footballer arg0;
        
        public createRequest() {
        }
        
        public createRequest(ClienteSoap.ServiceFootballer.footballer arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createResponse() {
        }
        
        public createResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSoap.ServiceFootballer.footballer arg0;
        
        public updateRequest() {
        }
        
        public updateRequest(ClienteSoap.ServiceFootballer.footballer arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateResponse() {
        }
        
        public updateResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicesChannel : ClienteSoap.ServiceFootballer.Services, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<ClienteSoap.ServiceFootballer.Services>, ClienteSoap.ServiceFootballer.Services {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.ServiceFootballer.listResponse ClienteSoap.ServiceFootballer.Services.list(ClienteSoap.ServiceFootballer.listRequest request) {
            return base.Channel.list(request);
        }
        
        public ClienteSoap.ServiceFootballer.footballer[] list() {
            ClienteSoap.ServiceFootballer.listRequest inValue = new ClienteSoap.ServiceFootballer.listRequest();
            ClienteSoap.ServiceFootballer.listResponse retVal = ((ClienteSoap.ServiceFootballer.Services)(this)).list(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.listResponse> ClienteSoap.ServiceFootballer.Services.listAsync(ClienteSoap.ServiceFootballer.listRequest request) {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.listResponse> listAsync() {
            ClienteSoap.ServiceFootballer.listRequest inValue = new ClienteSoap.ServiceFootballer.listRequest();
            return ((ClienteSoap.ServiceFootballer.Services)(this)).listAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.ServiceFootballer.deleteResponse ClienteSoap.ServiceFootballer.Services.delete(ClienteSoap.ServiceFootballer.deleteRequest request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string arg0) {
            ClienteSoap.ServiceFootballer.deleteRequest inValue = new ClienteSoap.ServiceFootballer.deleteRequest();
            inValue.arg0 = arg0;
            ClienteSoap.ServiceFootballer.deleteResponse retVal = ((ClienteSoap.ServiceFootballer.Services)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.deleteResponse> ClienteSoap.ServiceFootballer.Services.deleteAsync(ClienteSoap.ServiceFootballer.deleteRequest request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.deleteResponse> deleteAsync(string arg0) {
            ClienteSoap.ServiceFootballer.deleteRequest inValue = new ClienteSoap.ServiceFootballer.deleteRequest();
            inValue.arg0 = arg0;
            return ((ClienteSoap.ServiceFootballer.Services)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.ServiceFootballer.readResponse ClienteSoap.ServiceFootballer.Services.read(ClienteSoap.ServiceFootballer.readRequest request) {
            return base.Channel.read(request);
        }
        
        public ClienteSoap.ServiceFootballer.footballer read(string arg0) {
            ClienteSoap.ServiceFootballer.readRequest inValue = new ClienteSoap.ServiceFootballer.readRequest();
            inValue.arg0 = arg0;
            ClienteSoap.ServiceFootballer.readResponse retVal = ((ClienteSoap.ServiceFootballer.Services)(this)).read(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.readResponse> ClienteSoap.ServiceFootballer.Services.readAsync(ClienteSoap.ServiceFootballer.readRequest request) {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.readResponse> readAsync(string arg0) {
            ClienteSoap.ServiceFootballer.readRequest inValue = new ClienteSoap.ServiceFootballer.readRequest();
            inValue.arg0 = arg0;
            return ((ClienteSoap.ServiceFootballer.Services)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.ServiceFootballer.createResponse ClienteSoap.ServiceFootballer.Services.create(ClienteSoap.ServiceFootballer.createRequest request) {
            return base.Channel.create(request);
        }
        
        public bool create(ClienteSoap.ServiceFootballer.footballer arg0) {
            ClienteSoap.ServiceFootballer.createRequest inValue = new ClienteSoap.ServiceFootballer.createRequest();
            inValue.arg0 = arg0;
            ClienteSoap.ServiceFootballer.createResponse retVal = ((ClienteSoap.ServiceFootballer.Services)(this)).create(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.createResponse> ClienteSoap.ServiceFootballer.Services.createAsync(ClienteSoap.ServiceFootballer.createRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.createResponse> createAsync(ClienteSoap.ServiceFootballer.footballer arg0) {
            ClienteSoap.ServiceFootballer.createRequest inValue = new ClienteSoap.ServiceFootballer.createRequest();
            inValue.arg0 = arg0;
            return ((ClienteSoap.ServiceFootballer.Services)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.ServiceFootballer.updateResponse ClienteSoap.ServiceFootballer.Services.update(ClienteSoap.ServiceFootballer.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public bool update(ClienteSoap.ServiceFootballer.footballer arg0) {
            ClienteSoap.ServiceFootballer.updateRequest inValue = new ClienteSoap.ServiceFootballer.updateRequest();
            inValue.arg0 = arg0;
            ClienteSoap.ServiceFootballer.updateResponse retVal = ((ClienteSoap.ServiceFootballer.Services)(this)).update(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.updateResponse> ClienteSoap.ServiceFootballer.Services.updateAsync(ClienteSoap.ServiceFootballer.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ServiceFootballer.updateResponse> updateAsync(ClienteSoap.ServiceFootballer.footballer arg0) {
            ClienteSoap.ServiceFootballer.updateRequest inValue = new ClienteSoap.ServiceFootballer.updateRequest();
            inValue.arg0 = arg0;
            return ((ClienteSoap.ServiceFootballer.Services)(this)).updateAsync(inValue);
        }
    }
}
